services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - snack-hub-network

  snack-hub-production-app:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    container_name: snack-hub-production-api
    ports:
      - "8080:8080"
    networks:
      - snack-hub-network
    depends_on:
      - rabbitmq
  
  snack-hub-production-db:
    image: postgres:latest
    container_name: snack-hub-production-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SnackHub-ProductionService
    ports:
      - "5432:5432"
    networks:
      - snack-hub-network
    volumes:
      - snack-hub-production-db:/var/lib/postgresql/data

volumes:
  snack-hub-production-db:

networks:
  snack-hub-network:
    driver: bridge